---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/6/20 10:36
---

local LosePanel =class("LosePanel",UIPanel);

function LosePanel:awake()
    LosePanel.super.awake(self);
    print("LosePanel awake",self.rect);
end

return LosePanel;