---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/6/17 6:26
---
local PokerCard= require("game1.common.PokerCard")

local GamePanel =require("game1.ui.GamePanel");
---@type GamePanel
local gp=false;

---@class BossMgr
local BossMgr =class("BossMgr")


function BossMgr:init()

    if(not gp)then
        gp =GamePanel.inst;
    end

    self.turnCount =1;

    gp:show_turnCountTxt(utilFunc.numFormat(self.turnCount));


    gp:show_tagetAwardTxt(utilFunc.numFormat(self:getCurAwardDollar()))
    gp:show_tagetCoinTxt(utilFunc.numFormat(self:getCurTargetScore()))
    gp:show_bossNameTxt(self:getCurBossName())
end

function BossMgr:getCurTargetScore()
    return 450;
end
function BossMgr:getCurAwardDollar()
    return 4;
end
function BossMgr:getCurBossName()
    return "大盲注"
end


return BossMgr;