---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/6/17 6:23
---

local utilFunc=require("game1.utilFunc")
local HandSort ={}


local function sortPartFlower(hand_pokerCardArr,cFlower)
   local data= js.filter(hand_pokerCardArr,function (item) return item:getCFlower()==cFlower end);

    table.sort(data,function (a,b)
      return   a:getCPoint()>b:getCPoint();
    end)

    return data;
end

local function sortPartPoint(hand_pokerCardArr,cPoint)
    local data =js.filter(hand_pokerCardArr,function (item) return item:getCPoint()==cPoint end);

    table.sort(data,function (a,b)
        return  a:getCFlower() <b:getCFlower();
    end)

    return data;
end

function HandSort.sortByPoint(hand_pokerCardArr)
    table.sort(hand_pokerCardArr,function (a,b)
        return a:getCPoint()>b:getCPoint();
    end)

    local t ={};
    for i = 14, 2,-1 do
        local group =sortPartPoint(hand_pokerCardArr,i);
        js.push(t,unpack(group));
    end

    utilFunc.clearArr(hand_pokerCardArr);

    js.push(hand_pokerCardArr, unpack(t));

end

function HandSort.sortByFlower(hand_pokerCardArr)

    table.sort(hand_pokerCardArr,function (a,b)
        return a:getCFlower() <b:getCFlower();
    end)

    local spades=sortPartFlower(hand_pokerCardArr,CARD_Flower.spades);
    local hearts=sortPartFlower(hand_pokerCardArr,CARD_Flower.hearts);
    local clubs=sortPartFlower(hand_pokerCardArr,CARD_Flower.clubs);
    local diamonds=sortPartFlower(hand_pokerCardArr,CARD_Flower.diamonds);

    utilFunc.clearArr(hand_pokerCardArr);

    js.push(hand_pokerCardArr,unpack(spades));
    js.push(hand_pokerCardArr,unpack(hearts));
    js.push(hand_pokerCardArr,unpack(clubs));
    js.push(hand_pokerCardArr,unpack(diamonds));
end


return HandSort;