---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/6/19 15:01
---
---
---@class JokerSys
local JokerSys=class("JokerSys")


function JokerSys:init()

end

return JokerSys;