---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/6/19 15:01
---
---
---@class OtherSys
local OtherSys=class("OtherSys")


function OtherSys:init()

end

return OtherSys;