---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/6/17 6:42
---


local GamePanel =require("game1.ui.GamePanel");
---@type GamePanel
local gp=false;
---@class PlayerSys
local PlayerSys=class("PlayerSys");



function PlayerSys:ctor()

end

function PlayerSys:init()
    --发多少到手牌
    self.sendCount =7;
    --有多少美金
    self.moneyCount =5;
    --有多少筹码
    self.coinCount =2;
    --中奖牌型的管理
    self.awardMgr={};
    self:initAwardMgr();

    --弃牌次数
    self.dumpCount =4;
    --出牌次数
    self.drawPlayCount=2;

    if(not gp)then
        gp =GamePanel.inst;
    end

    gp:showDrawPlayCount(utilFunc.numFormat(self.drawPlayCount));
    gp:showDumpCount(utilFunc.numFormat(self.dumpCount));
    gp:show_coinTxt(utilFunc.numFormat(self.coinCount));
    gp:show_dollarTxt(utilFunc.numFormat(self.moneyCount));
end

function PlayerSys:addCoint(cointNum)
    self.coinCount=self.coinCount+cointNum;
    gp:show_coinTxt(utilFunc.numFormat(self.coinCount));
end

function PlayerSys:addMoneyCount(mNum)
    self.moneyCount=self.moneyCount+mNum;
    gp:show_dollarTxt(utilFunc.numFormat(self.moneyCount));
end

function PlayerSys:getCoinCount()
    return self.coinCount;
end

function PlayerSys:getDrawPlayCount()
    return self.drawPlayCount;
end

function PlayerSys:getDumpCount()
    return self.dumpCount;
end

function PlayerSys:reduceDumpCount()
    if(self.dumpCount >0)then
        self.dumpCount =self.dumpCount-1;
        gp:showDumpCount(utilFunc.numFormat(self.dumpCount));
        return true;
    else
        return false;
    end
end

function PlayerSys:reduceDrawPlayCount()
    if(self.drawPlayCount >0)then
        self.drawPlayCount =self.drawPlayCount-1;
        gp:showDrawPlayCount(utilFunc.numFormat(self.drawPlayCount));
        return true;
    else
        return false;
    end
end

function PlayerSys:initAwardMgr()

    local function initOneData(awardEnum,blue,red)
        local oneData={}
        oneData.lv =1;
        --中了多少次呢
        oneData.awardCount =0;

        oneData.awardEnum=awardEnum;
        --blue也是筹码
        oneData.blue=blue;
        --red的小倍率
        oneData.red=red;

        table.insert(self.awardMgr,oneData);
    end

    --high=2,5,1,
    --pair=3,10,2,
    --two_pair=4,20,2,
    --three=5,30,3,
    --straight=6,30,4
    --flush=7,35,4
    --fullHouse=8,40,4
    --four=9,60,7
    --straightFlush=10,100,8,

    --todo warn 这里枚举是硬编码
    initOneData(2,5,1);
    initOneData(3,10,2);
    initOneData(4,20,2);

    initOneData(5,30,3);
    initOneData(6,30,4);
    initOneData(7,35,4);

    initOneData(8,40,4);
    initOneData(9,60,7);
    initOneData(10,100,8);



    assert(#self.awardMgr==9);
end

--根据中奖类型获取，继承cointmessage
function PlayerSys:getAwardPointMessage(cardAwardEnum)
     local oneData =js.find(self.awardMgr,function (item) return item.awardEnum==cardAwardEnum end)

    if(oneData)then
        return oneData.blue,oneData.red,oneData.awardEnum,oneData.lv;
    else
        return 0,0,"","";
    end
end

function PlayerSys:getSendCount()
    return self.sendCount;
end

---要抽多少牌呢，销毁包括弃牌和出的牌
function PlayerSys:drawPokerCount(handCount)
    return self.sendCount -handCount;
end

return PlayerSys;