---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/6/17 6:16
---

---@class PokerCard
local PokerCard = class("PokerCard")

function PokerCard:ctor()
    --print("pocker card ctor");
end

function PokerCard:awake()
    self.pokerTrans = self.trans:Find("Point");
    self.backTrans = self.trans:Find("back");
    self.whiteBgImg = self.trans:GetComponent(typeof(Image));


    -- print("pocker car awake");
end

function PokerCard:init(cPoint, cFlower)
    --print("pc init");

    self.cPoint = cPoint;
    self.cFlower = cFlower;

    self.isSelect = false;
    self.isBack = true;
    self:freshBack();
    self:setPokerSp();
end

function PokerCard:calculatePoint()
    return self.cPoint;
end

function PokerCard:start()

end

function PokerCard:setSiblingIdx(luaIdx)

    self.trans:SetSiblingIndex(luaIdx-1);
end

function PokerCard:getCFlower()
    return self.cFlower
end

function PokerCard:getCPoint()
    return self.cPoint;
end

function PokerCard:onPointerClick()
    --todo 状态的再次巩固

    local parentName = self.trans.parent.name;
    if (parentName ~= "Hand") then
        return ;
    end

    if (not G1:canSelect()) then
        return ;
    end

    if (not G1:canSelect2(self)) then
        return ;
    end

    self.isSelect = not self.isSelect;
    self:freshSelect(self.isSelect);

    if (self.isSelect) then
        G1:selectAdd(self);
    else
        G1:selectRemove(self);
    end
    G1:pokerAwardResult();

    print("total select len " .. tostring(#G1.selectPokers) .. "sbIdx is " ..tostring(self:getTransIdx()))
end

--获取索引值，因为父亲会变，必须动态获取
function PokerCard:getTransIdx()
    local idx =self.trans:GetSiblingIndex();
    return idx;
end

function PokerCard:setPokerSp()
    self.pokerTrans:GetComponent(typeof(Image)).sprite = G1:getPockerSpByEnum(self.cPoint, self.cFlower);
end

function PokerCard:changeBack(show)
    self.isBack = not show;
    self:freshBack();
end

function PokerCard:freshSelect(isSelect)
    if (isSelect) then
        self.whiteBgImg.color = Color.yellow;
    else
        self.whiteBgImg.color = Color.white;
    end
end

function PokerCard:freshBack()
    local go = self.backTrans.gameObject;
    if (self.isBack) then
        go:SetActive(true);
    else
        go:SetActive(false);
    end
end

return PokerCard;